/**
 * Ruby extractor.
 *
 * Ruby resists static analysis, so this leans on two things that do hold in
 * practice:
 *   1. `x = Foo.new` types a local exactly.
 *   2. Rails associations follow naming conventions, so `belongs_to :donor`
 *      can be turned into a real method returning a real class.
 *
 * Methods invented from a DSL are marked `generated: true` and annotated with
 * the macro that produced them, so nothing downstream mistakes them for code
 * that exists on disk.
 */

/** `line_items` -> `LineItem`. Deliberately simple; irregulars are not covered. */
export function classify(name) {
  return singularize(name)
    .split('_')
    .filter(Boolean)
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join('');
}

export function singularize(word) {
  if (/ies$/.test(word)) return word.replace(/ies$/, 'y');
  if (/(ch|sh|ss|x|z)es$/.test(word)) return word.replace(/es$/, '');
  // `status`, `address`, `analysis` are singular already despite the trailing s.
  if (/s$/.test(word) && !/(ss|us|is)$/.test(word)) return word.replace(/s$/, '');
  return word;
}

const ASSOCIATION_MACROS = new Set(['belongs_to', 'has_one', 'has_many', 'has_and_belongs_to_many']);
const COLLECTION_MACROS = new Set(['has_many', 'has_and_belongs_to_many']);
const ATTR_MACROS = new Set(['attr_reader', 'attr_writer', 'attr_accessor']);

function text(node, src) {
  return src.slice(node.startIndex, node.endIndex);
}

function childByField(node, field) {
  return node.childForFieldName(field) ?? null;
}

/** `:donor` -> `donor`, `"donor"` -> `donor` */
function symbolArgName(node, src) {
  if (!node) return null;
  const raw = text(node, src).trim();
  if (raw.startsWith(':')) return raw.slice(1);
  const unquoted = raw.replace(/^['"]|['"]$/g, '');
  return /^[a-z_][\w]*[?!=]?$/i.test(unquoted) ? unquoted : null;
}

function argNodes(callNode) {
  const args = childByField(callNode, 'arguments');
  if (!args) return [];
  const out = [];
  for (let i = 0; i < args.namedChildCount; i++) {
    const c = args.namedChild(i);
    if (c) out.push(c);
  }
  return out;
}

export function extractRuby(tree, src, ctx = {}) {
  const symbols = [];
  const refs = [];
  const locals = [];
  const imports = [];

  const addSymbol = (s) => {
    s.tmpId = symbols.length;
    symbols.push(s);
    return s.tmpId;
  };

  const pos = (node) => ({
    start_line: node.startPosition.row + 1,
    end_line: node.endPosition.row + 1,
    start_byte: node.startIndex,
    end_byte: node.endIndex,
  });

  /** Turns a Rails macro call in a class body into the methods it defines. */
  function applyMacro(callNode, containerFqn, ownerName) {
    const macro = text(childByField(callNode, 'method'), src);
    const args = argNodes(callNode);
    const first = symbolArgName(args[0], src);

    const generated = (name, typeName, extra = {}) =>
      addSymbol({
        name,
        fqn: `${containerFqn}#${name}`,
        kind: 'method',
        container_fqn: containerFqn,
        type_name: typeName,
        signature: `${name}  # generated by ${macro}`,
        arity: 0,
        supertypes: [],
        modifiers: ['generated'],
        annotations: [macro],
        generated: true,
        ...extra,
        ...pos(callNode),
      });

    if (ASSOCIATION_MACROS.has(macro) && first) {
      const isCollection = COLLECTION_MACROS.has(macro);
      generated(first, classify(first), {
        modifiers: isCollection ? ['generated', 'collection'] : ['generated'],
      });
      if (!isCollection) generated(`${first}=`, classify(first));
      return true;
    }

    if (ATTR_MACROS.has(macro)) {
      for (const arg of args) {
        const name = symbolArgName(arg, src);
        if (!name) continue;
        if (macro !== 'attr_writer') generated(name, null);
        if (macro !== 'attr_reader') generated(`${name}=`, null);
      }
      return true;
    }

    if (macro === 'scope' && first) {
      addSymbol({
        name: first,
        fqn: `${containerFqn}.${first}`,
        kind: 'class_method',
        container_fqn: containerFqn,
        type_name: ownerName,
        signature: `${first}  # generated by scope`,
        arity: 0,
        supertypes: [],
        modifiers: ['generated'],
        annotations: ['scope'],
        generated: true,
        ...pos(callNode),
      });
      return true;
    }

    return false;
  }

  function walk(node, nest, scopeId, inClassBody, classScopeId) {
    if (node.type === 'class' || node.type === 'module') {
      const nameNode = childByField(node, 'name');
      if (!nameNode) return;
      const simpleName = text(nameNode, src);
      const nextNest = [...nest, simpleName];
      const fqn = nextNest.join('::');

      const supertypes = [];
      const superNode = childByField(node, 'superclass');
      if (superNode) {
        // The `superclass` node wraps the constant, hence the trim of `<`.
        const raw = text(superNode, src).replace(/^\s*<\s*/, '').trim();
        if (raw) supertypes.push(raw);
      }

      const id = addSymbol({
        name: simpleName,
        fqn,
        kind: node.type === 'module' ? 'module' : 'class',
        container_fqn: nest.length ? nest.join('::') : null,
        type_name: null,
        signature: `${node.type} ${fqn}`,
        arity: null,
        supertypes,
        modifiers: [],
        annotations: [],
        ...pos(node),
      });

      // Walked after the symbol exists, because `include Foo` appends to its
      // supertypes as it is encountered.
      const body = childByField(node, 'body');
      if (body) {
        for (let i = 0; i < body.namedChildCount; i++) {
          const c = body.namedChild(i);
          if (c) walk(c, nextNest, id, true, id);
        }
      }
      return;
    }

    if (node.type === 'method' || node.type === 'singleton_method') {
      const nameNode = childByField(node, 'name');
      if (!nameNode) return;
      const simpleName = text(nameNode, src);
      const containerFqn = nest.join('::') || null;
      const isSingleton = node.type === 'singleton_method';

      const params = [];
      const paramsNode = childByField(node, 'parameters');
      if (paramsNode) {
        for (let i = 0; i < paramsNode.namedChildCount; i++) {
          const p = paramsNode.namedChild(i);
          if (p) params.push(text(p, src).split(/[:=]/)[0].trim());
        }
      }

      const id = addSymbol({
        name: simpleName,
        fqn: `${containerFqn}${isSingleton ? '.' : '#'}${simpleName}`,
        kind: isSingleton ? 'class_method' : 'method',
        container_fqn: containerFqn,
        type_name: null,
        signature: `${isSingleton ? 'self.' : ''}${simpleName}(${params.join(', ')})`,
        arity: params.length,
        supertypes: [],
        modifiers: isSingleton ? ['singleton'] : [],
        annotations: [],
        ...pos(node),
      });

      const body = childByField(node, 'body');
      if (body) walk(body, nest, id, false, classScopeId);
      return;
    }

    if (node.type === 'call') {
      const methodNode = childByField(node, 'method');
      const receiverNode = childByField(node, 'receiver');
      const methodName = methodNode ? text(methodNode, src) : null;

      // Class-body DSL calls define things rather than call them.
      if (inClassBody && !receiverNode && methodName) {
        const containerFqn = nest.join('::') || null;
        if (methodName === 'include' || methodName === 'extend' || methodName === 'prepend') {
          const mod = argNodes(node)[0];
          if (mod && scopeId != null) {
            symbols[scopeId].supertypes = [...(symbols[scopeId].supertypes ?? []), text(mod, src)];
          }
          return;
        }
        if (containerFqn && applyMacro(node, containerFqn, nest[nest.length - 1])) return;
      }

      if (methodName) {
        refs.push({
          fromTmpId: scopeId,
          name: methodName,
          receiver: receiverNode ? text(receiverNode, src) : null,
          arity: argNodes(node).length,
          line: node.startPosition.row + 1,
          kind: methodName === 'new' && receiverNode ? 'new' : 'call',
        });
      }
      // Fall through so nested calls inside the receiver/arguments are seen.
    }

    if (node.type === 'assignment') {
      const left = childByField(node, 'left');
      const right = childByField(node, 'right');
      // `x = Foo.new` is the one assignment that types a variable with certainty.
      if (left && right && right.type === 'call') {
        const rmethod = childByField(right, 'method');
        const rrecv = childByField(right, 'receiver');
        if (rmethod && rrecv && text(rmethod, src) === 'new' && rrecv.type === 'constant') {
          locals.push({
            // An ivar outlives the method, so it belongs to the class scope.
            scopeTmpId: left.type === 'instance_variable' ? classScopeId : scopeId,
            name: text(left, src),
            type_name: text(rrecv, src),
          });
        }
      }
    }

    // A bare identifier in a method body is usually an implicit-self call.
    // These are noisy by nature, so the resolver drops the ones that match
    // nothing rather than reporting them as unresolved.
    if (node.type === 'identifier' && scopeId != null && !inClassBody) {
      const p = node.parent;
      const sameNode = (a, b) => a && b && a.startIndex === b.startIndex && a.endIndex === b.endIndex;
      const isCallMethod = p?.type === 'call' && sameNode(childByField(p, 'method'), node);
      const isAssignTarget = p?.type === 'assignment' && sameNode(childByField(p, 'left'), node);
      const isParam = p?.type === 'method_parameters' || p?.type === 'block_parameters';
      if (!isCallMethod && !isAssignTarget && !isParam) {
        refs.push({
          fromTmpId: scopeId,
          name: text(node, src),
          receiver: null,
          arity: 0,
          line: node.startPosition.row + 1,
          kind: 'ident_call',
        });
      }
    }

    if (node.type === 'call' && childByField(node, 'method')) {
      const m = text(childByField(node, 'method'), src);
      if ((m === 'require' || m === 'require_relative') && argNodes(node).length) {
        const arg = text(argNodes(node)[0], src).replace(/^['"]|['"]$/g, '');
        imports.push({ fqn: arg, simple: arg.split('/').pop(), is_wildcard: 0, is_static: 0 });
      }
    }

    for (let i = 0; i < node.namedChildCount; i++) {
      const c = node.namedChild(i);
      if (c) walk(c, nest, scopeId, inClassBody && node.type === 'body_statement', classScopeId);
    }
  }

  // Ruby runs plenty of code outside any class: RSpec describe/it blocks,
  // routes.rb, initializers. Without a file scope those are all orphans.
  const fileScope = addSymbol({
    name: (ctx.path ?? 'file').split('/').pop(),
    fqn: ctx.path ?? null,
    kind: 'file',
    container_fqn: null,
    type_name: null,
    signature: `file ${ctx.path ?? ''}`,
    arity: null,
    supertypes: [],
    modifiers: [],
    annotations: [],
    start_line: 1,
    end_line: tree.rootNode.endPosition.row + 1,
    start_byte: 0,
    end_byte: tree.rootNode.endIndex,
  });

  walk(tree.rootNode, [], fileScope, false, null);

  return { package: null, imports, symbols, refs, locals };
}
