#!/usr/bin/env bash
# scaffold-provenlens.sh -- create the folder tree and empty files of provenlens.
#
#   bash scaffold-provenlens.sh [--runtime | --tests] [target-dir]     (default: ./provenlens)
#
#   --runtime   only what is needed to run it: package.json, yarn.lock, bin/, src/   (43 files)
#   --tests     that, plus test/ and __fixtures__/                                  (192 files)
#   (no flag)   everything git tracks                                               (212 files)
#
# Structure only: every file is created empty. Nothing is overwritten, so it is safe to re-run
# after you have started filling files in. The files git marks executable are made executable.
# GENERATED by scripts/gen-structure.js from `git ls-files` -- edit that, not this.
set -euo pipefail

tier=all
root=provenlens
for arg in "$@"; do
  case "$arg" in
    --runtime) tier=runtime ;;
    --tests) tier=tests ;;
    -h|--help) sed -n '2,11p' "$0" | sed 's/^# \{0,1\}//'; exit 0 ;;
    -*) echo "unknown option: $arg" >&2; exit 2 ;;
    *) root=$arg ;;
  esac
done

wanted() {
  case "$tier" in
    all) return 0 ;;
    runtime) case "$1" in package.json|yarn.lock|bin/*|src/*) return 0 ;; esac ;;
    tests) case "$1" in package.json|yarn.lock|bin/*|src/*|test/*|__fixtures__/*) return 0 ;; esac ;;
  esac
  return 1
}

mkdir -p "$root"
cd "$root"

created=0; existing=0
while IFS= read -r f; do
  [ -n "$f" ] || continue
  wanted "$f" || continue
  mkdir -p "$(dirname "$f")"
  if [ -e "$f" ]; then existing=$((existing+1)); else : > "$f"; created=$((created+1)); fi
done <<'PATHS'
.github/dependabot.yml
.github/pull_request_template.md
.github/workflows/blast-radius.yml
.github/workflows/hygiene.yml
.github/workflows/resolution.yml
.github/workflows/review.yml
.github/workflows/security.yml
.github/workflows/tests.yml
.gitignore
LICENSE
README.md
SETUP.md
SETUP.vi.md
STRUCTURE.md
__fixtures__/bindings/app/kafka/audit_worker.rb
__fixtures__/bindings/app/workers/order_worker.rb
__fixtures__/bindings/src/graphql/orders.resolver.ts
__fixtures__/bindings/src/kafka_consumer.ts
__fixtures__/bindings/src/main/java/com/shop/events/OrderAudit.java
__fixtures__/bindings/src/main/java/com/shop/events/OrderEvents.java
__fixtures__/bindings/src/main/java/com/shop/graphql/OrderResolver.java
__fixtures__/bindings/src/main/java/com/shop/grpc/NotAService.java
__fixtures__/bindings/src/main/java/com/shop/grpc/OrderServiceImpl.java
__fixtures__/bindings/src/main/java/com/shop/kafka/OrderProducer.java
__fixtures__/bindings/src/main/java/com/shop/kafka/ShipmentListener.java
__fixtures__/bindings/src/main/java/com/shop/mapper/Order.java
__fixtures__/bindings/src/main/java/com/shop/mapper/OrderMapper.java
__fixtures__/bindings/src/main/java/com/shop/messaging/OrderListener.java
__fixtures__/bindings/src/main/java/com/shop/messaging/OrderPublisher.java
__fixtures__/bindings/src/main/java/com/shop/route/OrderRoute.java
__fixtures__/bindings/src/main/proto/orders.proto
__fixtures__/bindings/src/main/resources/db/migration/V1__create_orders.sql
__fixtures__/bindings/src/main/resources/db/migration/V2__add_orders_status.sql
__fixtures__/bindings/src/main/resources/graphql/schema.graphqls
__fixtures__/bindings/src/main/resources/mapper/OrderMapper.xml
__fixtures__/bindings/src/order_events_handler.ts
__fixtures__/bindings2/app/controllers/api/things_controller.rb
__fixtures__/bindings2/app/controllers/application_controller.rb
__fixtures__/bindings2/config/routes.rb
__fixtures__/bindings2/src/client/api.ts
__fixtures__/bindings2/src/main/java/com/p/Comment.java
__fixtures__/bindings2/src/main/java/com/p/Listeners2.java
__fixtures__/bindings2/src/main/java/com/p/OrderClient.java
__fixtures__/bindings2/src/main/java/com/p/OrderController.java
__fixtures__/bindings2/src/main/java/com/p/OrderResolver.java
__fixtures__/bindings2/src/main/java/com/p/OrderServiceImpl.java
__fixtures__/bindings2/src/main/java/com/p/Producer.java
__fixtures__/bindings2/src/main/java/com/p/SqsBits.java
__fixtures__/bindings2/src/main/java/com/p/UserDao.java
__fixtures__/bindings2/src/main/proto/orders.proto
__fixtures__/bindings2/src/main/resources/db/migration/V1__init.sql
__fixtures__/bindings2/src/main/resources/graphql/schema.graphqls
__fixtures__/bindings2/src/main/resources/mapper/UserMapper.xml
__fixtures__/java/com/acme/domain/Donation.java
__fixtures__/java/com/acme/lombok/Holder.java
__fixtures__/java/com/acme/lombok/Ledger.java
__fixtures__/java/com/acme/lombok/Receipt.java
__fixtures__/java/com/acme/lombok/Stamp.java
__fixtures__/java/com/acme/lombok/Store.java
__fixtures__/java/com/acme/lombok/Ticket.java
__fixtures__/java/com/acme/repo/DonationRepository.java
__fixtures__/java/com/acme/repo/JpaDonationRepository.java
__fixtures__/java/com/acme/report/DonationFormatter.java
__fixtures__/java/com/acme/service/BaseService.java
__fixtures__/java/com/acme/service/DonationService.java
__fixtures__/java/com/acme/service/DonationServiceImpl.java
__fixtures__/java/com/acme/web/DonationController.java
__fixtures__/java2/src/main/java/com/acme/a/Bar.java
__fixtures__/java2/src/main/java/com/acme/a/Base.java
__fixtures__/java2/src/main/java/com/acme/a/Color.java
__fixtures__/java2/src/main/java/com/acme/a/Entity.java
__fixtures__/java2/src/main/java/com/acme/a/Foo.java
__fixtures__/java2/src/main/java/com/acme/a/Helper.java
__fixtures__/java2/src/main/java/com/acme/a/Overloads.java
__fixtures__/java2/src/main/java/com/acme/x/Use.java
__fixtures__/ruby/app/controllers/application_controller.rb
__fixtures__/ruby/app/controllers/donations_controller.rb
__fixtures__/ruby/app/models/application_record.rb
__fixtures__/ruby/app/models/concerns/auditable.rb
__fixtures__/ruby/app/models/concerns/stampable.rb
__fixtures__/ruby/app/models/donation.rb
__fixtures__/ruby/app/models/donor.rb
__fixtures__/ruby/app/models/receipt.rb
__fixtures__/ruby/app/models/settings_store.rb
__fixtures__/ruby/app/services/donation_recorder.rb
__fixtures__/ruby/app/services/donor_notifier.rb
__fixtures__/ruby2/app/models/application_record.rb
__fixtures__/ruby2/app/models/auditable.rb
__fixtures__/ruby2/app/models/log_adapter.rb
__fixtures__/ruby2/app/models/point.rb
__fixtures__/ruby2/app/models/policy.rb
__fixtures__/ruby2/app/models/somewhere.rb
__fixtures__/ruby2/app/models/user.rb
__fixtures__/ruby2/lib/consumer.rb
__fixtures__/ruby2/lib/top.rb
__fixtures__/ruby2/lib/user_ext.rb
__fixtures__/ruby2/spec/user_spec.rb
__fixtures__/ts/node_modules/tiny-lib/index.d.ts
__fixtures__/ts/node_modules/tiny-lib/package.json
__fixtures__/ts/src/domain/donation.ts
__fixtures__/ts/src/domain/index.ts
__fixtures__/ts/src/lib/bundle.js
__fixtures__/ts/src/lib/format.js
__fixtures__/ts/src/lib/handlerUse.js
__fixtures__/ts/src/lib/handlers.js
__fixtures__/ts/src/lib/legacy.js
__fixtures__/ts/src/lib/legacyUse.js
__fixtures__/ts/src/repo/donationRepository.ts
__fixtures__/ts/src/repo/ledgerClient.ts
__fixtures__/ts/src/service/donationService.ts
__fixtures__/ts/src/web/donationController.ts
__fixtures__/ts/src/web/receipt.ts
__fixtures__/ts/tsconfig.json
__fixtures__/ts2/packages/core/lib/index.ts
__fixtures__/ts2/packages/core/package.json
__fixtures__/ts2/src/lib/anon.ts
__fixtures__/ts2/src/lib/appdef.ts
__fixtures__/ts2/src/lib/cc.ts
__fixtures__/ts2/src/lib/lib.ts
__fixtures__/ts2/src/ns/a.ts
__fixtures__/ts2/src/ns/index.ts
__fixtures__/ts2/src/types/api.d.ts
__fixtures__/ts2/src/use/use.ts
__fixtures__/ts2/tsconfig.base.json
__fixtures__/ts2/tsconfig.json
__fixtures__/unlinked/lib/many.rb
__fixtures__/unlinked/lib/order.rb
__fixtures__/unlinked/lib/service.rb
__fixtures__/unlinked/lib/user.rb
__fixtures__/unlinked/spec/order_spec.rb
__fixtures__/unlinked/src/a.ts
__fixtures__/unlinked/src/b.ts
__fixtures__/unlinked/src/go.ts
__fixtures__/vendored/.gitignore
__fixtures__/vendored/packages/node_modules/@acme/engine/generated/legacy.js
__fixtures__/vendored/packages/node_modules/@acme/engine/index.js
__fixtures__/vendored/src/app.js
action.yml
bin/provenlens.js
package.json
scripts/ast.js
scripts/bench.js
scripts/gen-structure.js
scripts/protect-main.sh
scripts/scaffold-provenlens.sh
src/ambient.js
src/bindings/camel.js
src/bindings/flyway.js
src/bindings/graphql.js
src/bindings/grpc.js
src/bindings/http.js
src/bindings/index.js
src/bindings/kafka.js
src/bindings/mybatis.js
src/bindings/springevent.js
src/bindings/sqs.js
src/bindings/text.js
src/db.js
src/doctor.js
src/extract/index.js
src/extract/java.js
src/extract/ruby.js
src/extract/typescript.js
src/format.js
src/heap.js
src/hook.js
src/indexer.js
src/insight.js
src/install.js
src/jvm.js
src/lang.js
src/mcp.js
src/project.js
src/query.js
src/quiet.js
src/resolve/java.js
src/resolve/ruby.js
src/resolve/typescript.js
src/schema/rails.js
src/server.js
src/ui/app.html
src/unlinked.js
src/watch.js
src/why.js
src/workspace.js
test/bindings-review.test.js
test/bindings.test.js
test/core-fixes.test.js
test/doctor.test.js
test/helpers.js
test/hook.test.js
test/http-routes.test.js
test/index-lock.test.js
test/insight.test.js
test/java-review.test.js
test/java.test.js
test/jvm-fields.test.js
test/mixed.test.js
test/multirepo.test.js
test/regressions.test.js
test/ruby-review.test.js
test/ruby.test.js
test/runtime.test.js
test/schema.test.js
test/server.test.js
test/structure.test.js
test/typescript-review.test.js
test/typescript.test.js
test/uninstall.test.js
test/unlinked.test.js
test/vendored.test.js
yarn.lock
PATHS

for f in bin/provenlens.js scripts/ast.js scripts/bench.js scripts/gen-structure.js scripts/protect-main.sh scripts/scaffold-provenlens.sh; do
  if [ -e "$f" ]; then chmod +x "$f"; fi
done

echo "$root ($tier): $created file(s) created, $existing already present"
